### ISSUE TITLE
Error trying to use GoogleCloudPrint.dll in Windows Forms application targeting .NET Framework 4.6.1

### ISSUE THREAD

**Issue by awerber** [lppkarl/GoogleCloudPrintApi#23]
**I got past this, please see next comment.**

As you can tell for the title I get an error when trying to use the DLL. Here's the error:

System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Net.Sockets, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=GoogleCloudPrintApi
  StackTrace:
   at GoogleCloudPrintApi.GoogleCloudPrintClient..ctor(GoogleCloudPrintOAuth2Provider oAuth2Provider, Token token) in C:\NotMyCode\GoogleCloudPrintApi-master\GoogleCloudPrintApi\GoogleCloudPrintClient.cs:line 33
   at TestUsingGCPApi.Form1.GetClient(GoogleCloudPrintOAuth2Provider oauthProvider) in C:\MyCode\TestUsingGCPApi\Form1.cs:line 69
   at TestUsingGCPApi.Form1.btnSharePrinter_Click(Object sender, EventArgs e) in C:\MyCode\TestUsingGCPApi\Form1.cs:line 43
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at TestUsingGCPApi.Program.Main() in C:\MyCode\TestUsingGCPApi\Program.cs:line 19

The error happens when trying to create a GoogleCloudPrintClient. The provider and token are fine. The provider is creating using the credentials from my 'other' type project. I can run the Samples code from this repository and a client is created.

I think the problem I'm facing is that the Samples project here is targeted to .NET Core, and I need the DLLs from that package in my project. When I try to install Microsoft.NETCore.App in my windows forms project, I get another error:

Could not install package 'Microsoft.NETCore.App 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

My ultimate goal is to create a Windows Forms program that can be used for administration of printers for Google Cloud Print. One function I want to implement in my program is to make a Share invitation. I know that this can be done from https://www.google.com/cloudprint#printers, but I would like to simplify this process for our administrators.

Any leads on how to fix this problem would be appreciated.

**Comment by awerber** [comment]
I got past my problems with file not found by installing the packages used by the API DLL project, and any other package with the name of the file that could not be found.

Unfortunately, there's still a problem. When I call client.SharePrinterAsync(req).Result the program hangs at the point that await UpdateTokenAsync(cancellationToken); (in GoogleCloudPrintClient.cs) exits. My UI  pops up and becomes totally unresponsive, I have to click the stop debugging button in VS 2017 to exit.

Any help would be greatly appreciated.

**Comment by karlwancl** [comment]
@awerber It probably because deadlock occurs when calling the api synchronously in winform/wpf application. The latest version should fix the issue, please check if it works.

**Comment by awerber** [comment]
Yes it works. Thank you.
